# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# zhishu.py
# Created on: 2023-02-13 13:47:01.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module

import arcpy

from arcpy import env
from arcpy.sa import *

env.workspace=r"O:\93task\DATA\CORE"
# Local variables:
#                                                                                                           改日期
result_NIR_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\map\\result_NIR.tif"
result_Red_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\map\\result_Red.tif"
result_Green_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\map\\result_Green.tif"
result_RedEdge_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\map\\result_RedEdge.tif"
result_Blue_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\map\\result_Blue.tif"
v704ndvi_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704ndvi.tif"
#result_Blue_tif = "O:\\93task\\DATA\\CORE\\0704dgp_hxdk100m\\map\\result_Blue.tif"
v704evi_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704evi.tif"
v704SR_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704SR.tif"
#result_RedEdge_tif = "O:\\93task\\DATA\\CORE\\0704dgp_hxdk100m\\map\\result_RedEdge.tif"
v704mtci_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704mtci.tif"
#result_Green_tif = "O:\\93task\\DATA\\CORE\\0704dgp_hxdk100m\\map\\result_Green.tif"
v704gndvi_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704gndvi.tif"
v704ndre_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704ndre.tif"
v704lci_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704lci.tif"
v704cigren_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704cigren.tif"
v704cired_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704cired.tif"
v704evi2_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704evi2.tif"
v704mndvi_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704mndvi.tif"
v704mndvire_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704mndvire.tif"
v704msr_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704msr.tif"
v704msrre_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704msrre.tif"
v704ndvire_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704ndvire.tif"
v704rtvi_tif = "O:\\93task\\DATA\\CORE\\0924dgp_hxdk100m\\tif\\704rtvi.tif"


# Process: 栅格计算器
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" - \"%result_Red.tif%\") / (\"%result_NIR.tif%\" + \"%result_Red.tif%\")", v704ndvi_tif)
NDVI = ((Raster(result_NIR_tif) - Raster(result_Red_tif)) / (Raster(result_NIR_tif) + Raster(result_Red_tif)))
NDVI.save(v704ndvi_tif)
print("ndviok")

# Process: 栅格计算器 (2)
#arcpy.gp.RasterCalculator_sa("2.5 * (\"%result_NIR.tif%\" - \"%result_Red.tif%\") / (\"%result_NIR.tif%\" + 6 * \"%result_Red.tif%\" - 7.5 * \"%result_Blue.tif%\" + 1)", v704evi_tif)
evi = (2.5 * (Raster(result_NIR_tif) - Raster(result_Red_tif)) / (Raster(result_NIR_tif) + 6 * Raster(result_Red_tif) - 7.5 * Raster(result_Blue_tif) + 1))
evi.save(v704evi_tif)
print("eviok")
# Process: 栅格计算器 (3)
#arcpy.gp.RasterCalculator_sa("\"%result_NIR.tif%\" / \"%result_Red.tif%\"", v704SR_tif)
sr = Raster(result_NIR_tif) / Raster(result_Red_tif)
sr.save(v704SR_tif)
print("srok")
# Process: 栅格计算器 (4)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" - \"%result_RedEdge.tif%\") / (\"%result_RedEdge.tif%\" - \"%result_Red.tif%\")", v704mtci_tif)
mtci = ((Raster(result_NIR_tif) - Raster(result_RedEdge_tif)) / (Raster(result_RedEdge_tif) - Raster(result_Red_tif)))
mtci.save(v704mtci_tif)
print("mtciok")
# Process: 栅格计算器 (5)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" - \"%result_Green.tif%\") / (\"%result_NIR.tif%\" + \"%result_Green.tif%\")", v704gndvi_tif)
gndvi = (Raster(result_NIR_tif) - Raster(result_Green_tif)) / (Raster(result_NIR_tif) + Raster(result_Green_tif))
gndvi.save(v704gndvi_tif)
print("gndviok")
# Process: 栅格计算器 (6)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" - \"%result_RedEdge.tif%\") / (\"%result_NIR.tif%\" + \"%result_RedEdge.tif%\")", v704ndre_tif)
ndre = (Raster(result_NIR_tif) - Raster(result_RedEdge_tif)) / (Raster(result_NIR_tif) + Raster(result_RedEdge_tif))
ndre.save(v704ndre_tif)
print("ndreok")
# Process: 栅格计算器 (7)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" - \"%result_RedEdge.tif%\") / (\"%result_NIR.tif%\" + \"%result_Red.tif%\")", v704lci_tif)
lci = (Raster(result_NIR_tif) - Raster(result_RedEdge_tif)) / (Raster(result_NIR_tif) + Raster(result_Red_tif))
lci.save(v704lci_tif)
print("lciok")
# Process: 栅格计算器 (8)
#arcpy.gp.RasterCalculator_sa("\"%result_NIR.tif%\" / \"%result_Green.tif%\" - 1", v704cigren_tif)
cigren = (Raster(result_NIR_tif) / Raster(result_Green_tif)) - 1
cigren.save(v704cigren_tif)
print("cigrenok")
# Process: 栅格计算器 (9)
#arcpy.gp.RasterCalculator_sa("\"%result_NIR.tif%\" / \"%result_RedEdge.tif%\" - 1", v704cired_tif)
cired = (Raster(result_NIR_tif) / Raster(result_RedEdge_tif)) -1
cired.save(v704cired_tif)
print("ciredok")
# Process: 栅格计算器 (10)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" - \"%result_Red.tif%\") / (1 + \"%result_NIR.tif%\" + 2.4 * \"%result_Red.tif%\")", v704evi2_tif)
evi2 = (Raster(result_NIR_tif) - Raster(result_Red_tif)) / (1 + Raster(result_NIR_tif) + 2.4 * Raster(result_Red_tif))
evi2.save(v704evi2_tif)
print("evi2ok")
# Process: 栅格计算器 (11)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" - \"%result_Red.tif%\") / (\"%result_NIR.tif%\" + \"%result_Red.tif%\" - 2 * \"%result_Blue.tif%\")", v704mndvi_tif)
mndvi = (Raster(result_NIR_tif) - Raster(result_Red_tif)) / (Raster(result_NIR_tif) + Raster(result_Red_tif) - 2 * Raster(result_Blue_tif))
mndvi.save(v704mndvi_tif)
print("mndviok")
# Process: 栅格计算器 (12)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" - \"%result_RedEdge.tif%\") / (\"%result_NIR.tif%\" + \"%result_RedEdge.tif%\" - 2 * \"%result_Blue.tif%\")", v704mndvire_tif)
mndvire = (Raster(result_NIR_tif) - Raster(result_RedEdge_tif)) / (Raster(result_NIR_tif) + Raster(result_RedEdge_tif) - 2 * Raster(result_Blue_tif))
mndvire.save(v704mndvire_tif)
print("mndvireok")
# Process: 栅格计算器 (13)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" / \"%result_Red.tif%\" - 1) / SquareRoot(\"%result_NIR.tif%\" / \"%result_Red.tif%\" + 1)", v704msr_tif)
msr = ((Raster(result_NIR_tif) / Raster(result_Red_tif) )- 1) / (SquareRoot((Raster(result_NIR_tif) / Raster(result_Red_tif)) + 1))
msr.save(v704msr_tif)
print("msrok")

# Process: 栅格计算器 (14)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" / \"%result_RedEdge.tif%\" - 1) / SquareRoot(\"%result_NIR.tif%\" / \"%result_RedEdge.tif%\" + 1)", v704msrre_tif)
msrre = ((Raster(result_NIR_tif) / Raster(result_RedEdge_tif) )-1) / (SquareRoot((Raster(result_NIR_tif) / Raster(result_RedEdge_tif)) + 1))
msrre.save(v704msrre_tif)
print("msrreok")
# Process: 栅格计算器 (15)
#arcpy.gp.RasterCalculator_sa("(\"%result_NIR.tif%\" - \"%result_RedEdge.tif%\") / (\"%result_NIR.tif%\" + \"%result_RedEdge.tif%\")", v704ndvire_tif)
ndvire = (Raster(result_NIR_tif) - Raster(result_RedEdge_tif)) / (Raster(result_NIR_tif) + Raster(result_RedEdge_tif))
ndvire.save(v704ndvire_tif)
print("ndvireok")
# Process: 栅格计算器 (16)
#arcpy.gp.RasterCalculator_sa("100 * (\"%result_NIR.tif%\" - \"%result_RedEdge.tif%\") - 10 * (\"%result_NIR.tif%\" - \"%result_Green.tif%\")", v704rtvi_tif)
rtvi = (100 * (Raster(result_NIR_tif) - Raster(result_RedEdge_tif))) - (10 * (Raster(result_NIR_tif) - Raster(result_Green_tif)))
rtvi.save(v704rtvi_tif)
print("JSok")

#                                                                                   改改改改改改改数字
NDVI1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\NDVI7.tif"
EVI1_nc1= "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\EVI7.tif"
SR1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\SR7.tif"
MTCI1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\MTCI7.tif"
GNDVI1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\GNDVI7.tif"
NDRE1_nc1= "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\NDRE7.tif"
LCI1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\LCI7.tif"
CIgreen1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\CIgreen7.tif"
CIred1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\CIred7.tif"
EVI21_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\EVI27.tif"
Mndvi1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\Mndvi7.tif"
mNDVIre1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\mNDVIre7.tif"
MSR1_nc1= "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\MSR7.tif"
MSRre1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\MSRre7.tif"
NDVIre1_nc1 = "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\NDVIre7.tif"
RTVI1_nc1= "O:\\93task\\DATA\\CORE\\0627dgp_hxdk100m\\tif\\RTVI7.tif"

#                                                                                   改改改改改改改数字
NDVI1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\NDVI7.nc"
EVI1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\EVI7.nc"
SR1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\SR7.nc"
MTCI1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\MTCI7.nc"
GNDVI1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\GNDVI7.nc"
NDRE1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\NDRE7.nc"
LCI1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\LCI7.nc"
CIgreen1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\CIgreen7.nc"
CIred1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\CIred7.nc"
EVI21_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\EVI27.nc"
Mndvi1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\Mndvi7.nc"
mNDVIre1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\mNDVIre7.nc"
MSR1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\MSR7.nc"
MSRre1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\MSRre7.nc"
NDVIre1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\NDVIre7.nc"
RTVI1_nc = "O:\\93task\\DATA\\CORE\\0728dgp_hxdk100m\\tif\\RTVI7.nc"


# Process: 重采样
arcpy.Resample_management(v704ndvi_tif, NDVI1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704evi_tif, EVI1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704SR_tif, SR1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704mtci_tif, MTCI1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704gndvi_tif, GNDVI1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704ndre_tif, NDRE1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704lci_tif, LCI1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704cigren_tif, CIgreen1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704cired_tif, CIred1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704evi2_tif, EVI21_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704mndvi_tif, Mndvi1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704mndvire_tif, mNDVIre1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704msr_tif , MSR1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704msrre_tif, MSRre1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704ndvire_tif, NDVIre1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
arcpy.Resample_management(v704rtvi_tif, RTVI1_nc1, "2.13449999999902E-06 2.13449999999902E-06", "BILINEAR")
print("重采样ok")
# Process: 栅格转 NetCDF
#                                                                                   改改改改改改改数字
arcpy.RasterToNetCDF_md(NDVI1_nc1, NDVI1_nc, "NDVI7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(EVI1_nc1, EVI1_nc, "EVI7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(SR1_nc1, SR1_nc, "SR7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(MTCI1_nc1, MTCI1_nc, "MTCI7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(GNDVI1_nc1, GNDVI1_nc, "GNDVI7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(NDRE1_nc1, NDRE1_nc, "NDRE7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(LCI1_nc1, LCI1_nc, "LCI7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(CIgreen1_nc1, CIgreen1_nc, "CIgreen7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(CIred1_nc1, CIred1_nc, "CIred7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(EVI21_nc1, EVI21_nc, "EVI27", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(Mndvi1_nc1, Mndvi1_nc, "Mndvi7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(mNDVIre1_nc1, mNDVIre1_nc, "mNDVIre7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(MSR1_nc1, MSR1_nc, "MSR7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(MSRre1_nc1, MSRre1_nc, "MSRre7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(NDVIre1_nc1, NDVIre1_nc, "NDVIre7", "", "lon", "lat", "", "", "0")
arcpy.RasterToNetCDF_md(RTVI1_nc1, RTVI1_nc, "RTVI7", "", "lon", "lat", "", "", "0")
print("NCok")
